import type { DaxMeasure, DaxUdf, DaxPackage } from "@/types"

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces)
  return text
    .split("\n")
    .map((line) => (line.trim() === "" ? "" : pad + line))
    .join("\n")
}

function emitMeasure(m: DaxMeasure): string {
  const lines: string[] = []
  // Indent DAX expression by 12 spaces (measure body standard)
  const daxIndented = indent(m.daxExpression.trimEnd(), 12)
  lines.push(`    measure '${m.displayName}' =`)
  lines.push(daxIndented)
  lines.push("")
  if (m.formatString) {
    lines.push(`        formatString: ${m.formatString}`)
  }
  if (m.description) {
    lines.push(`        description: """${m.description}"""`)
  }
  if (m.displayFolder) {
    lines.push(`        displayFolder: ${m.displayFolder}`)
  }
  if (m.isHidden) {
    lines.push(`        isHidden`)
  }
  return lines.join("\n")
}

function emitUdf(u: DaxUdf): string {
  const lines: string[] = []
  const daxIndented = indent(u.daxExpression.trimEnd(), 12)
  lines.push(`    measure '${u.displayName}' =`)
  lines.push(daxIndented)
  lines.push("")
  if (u.description) {
    lines.push(`        description: """${u.description}"""`)
  }
  return lines.join("\n")
}

export function generateTmdl(
  selectedMeasures: DaxMeasure[],
  selectedUdfs: DaxUdf[],
  selectedPackages: DaxPackage[],
  allMeasures: DaxMeasure[],
  allUdfs: DaxUdf[]
): string {
  // 1. Resolve packages into their constituent measures and UDFs
  const resolvedMeasures: DaxMeasure[] = []
  const resolvedUdfs: DaxUdf[] = []

  for (const pkg of selectedPackages) {
    for (const mid of pkg.measureIds) {
      const m = allMeasures.find((x) => x.id === mid)
      if (m) resolvedMeasures.push(m)
    }
    for (const uid of pkg.udfIds) {
      const u = allUdfs.find((x) => x.id === uid)
      if (u) resolvedUdfs.push(u)
    }
  }

  // 2. Merge and deduplicate measures
  const measureMap = new Map<string, DaxMeasure>()
  for (const m of [...resolvedMeasures, ...selectedMeasures]) {
    measureMap.set(m.id, m)
  }

  // 3. Merge and deduplicate UDFs
  const udfMap = new Map<string, DaxUdf>()
  for (const u of [...resolvedUdfs, ...selectedUdfs]) {
    udfMap.set(u.id, u)
  }

  const allSelectedMeasures = Array.from(measureMap.values())
  const allSelectedUdfs = Array.from(udfMap.values())

  // 4. Group by tableName
  const tableGroups = new Map<string, { measures: DaxMeasure[]; udfs: DaxUdf[] }>()

  for (const m of allSelectedMeasures) {
    if (!tableGroups.has(m.tableName)) {
      tableGroups.set(m.tableName, { measures: [], udfs: [] })
    }
    tableGroups.get(m.tableName)!.measures.push(m)
  }

  for (const u of allSelectedUdfs) {
    if (!tableGroups.has(u.tableName)) {
      tableGroups.set(u.tableName, { measures: [], udfs: [] })
    }
    tableGroups.get(u.tableName)!.udfs.push(u)
  }

  if (tableGroups.size === 0) {
    return "// No items selected."
  }

  const totalCount = allSelectedMeasures.length + allSelectedUdfs.length
  const timestamp = new Date().toISOString()

  // 5. Emit TMDL
  const blocks: string[] = []

  // Header comment
  blocks.push(
    `// Generated by DAX Library — ${timestamp}`,
    `// Items: ${totalCount} (${allSelectedMeasures.length} measure${allSelectedMeasures.length !== 1 ? "s" : ""}, ${allSelectedUdfs.length} function${allSelectedUdfs.length !== 1 ? "s" : ""})`,
    ``
  )

  for (const [tableName, group] of tableGroups) {
    blocks.push(`table '${tableName}'`)
    for (const m of group.measures) {
      blocks.push(emitMeasure(m))
    }
    for (const u of group.udfs) {
      blocks.push(emitUdf(u))
    }
    blocks.push("")
  }

  return blocks.join("\n").trimEnd()
}
