import type { DaxMeasure, DaxUdf, DaxPackage } from "@/types"

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces)
  return text
    .split("\n")
    .map((line) => (line.trim() === "" ? "" : pad + line))
    .join("\n")
}

function emitMeasure(m: DaxMeasure): string {
  const lines: string[] = []
  if (m.description) {
    lines.push(`        /// ${m.description}`)
  }
  const daxIndented = indent(m.daxExpression.trimEnd(), 16)
  lines.push(`        measure '${m.displayName}' =`)
  lines.push(daxIndented)
  lines.push("")
  if (m.formatString) {
    lines.push(`            formatString: ${m.formatString}`)
  }
  if (m.displayFolder) {
    lines.push(`            displayFolder: ${m.displayFolder}`)
  }
  if (m.isHidden) {
    lines.push(`            isHidden`)
  }
  return lines.join("\n")
}

function emitUdf(u: DaxUdf): string {
  const lines: string[] = []
  if (u.description) {
    lines.push(`/// ${u.description}`)
  }
  const bodyIndented = indent(u.daxExpression.trimEnd(), 8)
  lines.push(`function '${u.displayName}' =`)
  lines.push(`    (${u.parameters}) =>`)
  lines.push(bodyIndented)
  return lines.join("\n")
}

export function generateTmdl(
  selectedMeasures: DaxMeasure[],
  selectedUdfs: DaxUdf[],
  selectedPackages: DaxPackage[],
  allMeasures: DaxMeasure[],
  allUdfs: DaxUdf[]
): string {
  // 1. Resolve packages into their constituent measures and UDFs
  const resolvedMeasures: DaxMeasure[] = []
  const resolvedUdfs: DaxUdf[] = []

  for (const pkg of selectedPackages) {
    for (const mid of pkg.measureIds) {
      const m = allMeasures.find((x) => x.id === mid)
      if (m) resolvedMeasures.push(m)
    }
    for (const uid of pkg.udfIds) {
      const u = allUdfs.find((x) => x.id === uid)
      if (u) resolvedUdfs.push(u)
    }
  }

  // 2. Merge and deduplicate measures
  const measureMap = new Map<string, DaxMeasure>()
  for (const m of [...resolvedMeasures, ...selectedMeasures]) {
    measureMap.set(m.id, m)
  }

  // 3. Merge and deduplicate UDFs
  const udfMap = new Map<string, DaxUdf>()
  for (const u of [...resolvedUdfs, ...selectedUdfs]) {
    udfMap.set(u.id, u)
  }

  const allSelectedMeasures = Array.from(measureMap.values())
  const allSelectedUdfs = Array.from(udfMap.values())

  if (allSelectedMeasures.length === 0 && allSelectedUdfs.length === 0) {
    return "// No items selected."
  }

  const totalCount = allSelectedMeasures.length + allSelectedUdfs.length
  const timestamp = new Date().toISOString()

  const blocks: string[] = []

  // Header comment
  blocks.push(
    `// Generated by DAX Library — ${timestamp}`,
    `// Items: ${totalCount} (${allSelectedMeasures.length} measure${allSelectedMeasures.length !== 1 ? "s" : ""}, ${allSelectedUdfs.length} function${allSelectedUdfs.length !== 1 ? "s" : ""})`,
    ``
  )

  // 4. Emit measures inside a single createOrReplace block with ref table groups
  if (allSelectedMeasures.length > 0) {
    // Group by tableName
    const tableGroups = new Map<string, DaxMeasure[]>()
    for (const m of allSelectedMeasures) {
      if (!tableGroups.has(m.tableName)) {
        tableGroups.set(m.tableName, [])
      }
      tableGroups.get(m.tableName)!.push(m)
    }

    blocks.push(`createOrReplace`)
    blocks.push(``)
    for (const [tableName, measures] of tableGroups) {
      blocks.push(`    ref table '${tableName}'`)
      blocks.push(``)
      for (const m of measures) {
        blocks.push(emitMeasure(m))
        blocks.push(``)
      }
    }
  }

  // 5. Emit UDFs as top-level function objects (model-level, not table-scoped)
  if (allSelectedUdfs.length > 0) {
    for (const u of allSelectedUdfs) {
      blocks.push(emitUdf(u))
      blocks.push(``)
    }
  }

  return blocks.join("\n").trimEnd()
}
